### ISSUE TITLE
https://roblox.com/support

### ISSUE THREAD

**Issue by LabyCatUser** [maleahcya/help-hacked-roblox-account#1]
https://roblox.com/support

**Comment by kanaanahmad** [comment]
l it the

**Comment by gh-bako** [comment]
r/ihadastroke

**Comment by maleahcya** [comment]
I FORGOT I POSTED RHIS but i got my account back like a few months ago it’s been hacked since like 2019 💀 thank everyone though God bless don’t be afraid of following God and the truth

**Comment by maleahcya** [comment]
idk why i made a github tbh
